### ISSUE TITLE
No response from the bot...

### ISSUE THREAD

**Issue by ghost** [wuaster/Discord-with-Watson#1]
Hey, I appreciate your work. I made all the files that were told, and the bot has come online. But whenever I type ***hello** nothing happens. Is there anything I might have missed?

**Comment by wuaster** [comment]
Hi! It's likely due to the fact the Discord has updated their API. This project is outdated by now and I won't be maintaining it. Discord.js v14 is out now and has made the switch to Discord API v10. But that shouldn't stop you from creating the bot! There's a guide here: https://discordjs.guide/. It's the official documentation and they do an excellent job of explaining things at a beginner level.

Nevertheless, I appreciate you going through this project.

**Comment by ghost** [comment]
Ohh ok.
Thanks for replying. :D
